"""Initial migration 2

Revision ID: 06da90558885
Revises: 
Create Date: 2025-09-20 16:08:40.629615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06da90558885'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('tag', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('breed', sa.String(length=255), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('lot', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SOLD', 'DEAD', 'CULLED', name='animalstatus', native_enum=False), nullable=False),
    sa.Column('photo_url', sa.String(length=1024), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'tag', name='ux_animals_tenant_tag')
    )
    op.create_index(op.f('ix_animals_tenant_id'), 'animals', ['tenant_id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('owner_type', sa.Enum('ANIMAL', 'HEALTH_EVENT', name='ownertype', native_enum=False), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('storage_key', sa.String(length=2048), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'owner_type', 'owner_id', 'position', name='ux_attach_owner_pos')
    )
    op.create_index(op.f('ix_attachments_owner_id'), 'attachments', ['owner_id'], unique=False)
    op.create_index(op.f('ix_attachments_tenant_id'), 'attachments', ['tenant_id'], unique=False)
    op.create_table('buyers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='ux_buyers_tenant_name')
    )
    op.create_index(op.f('ix_buyers_tenant_id'), 'buyers', ['tenant_id'], unique=False)
    op.create_table('memberships',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'WORKER', 'VETERINARIAN', name='role', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'tenant_id'),
    sa.UniqueConstraint('user_id', 'tenant_id', name='ux_memberships_user_tenant')
    )
    op.create_table('milk_deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('buyer_id', sa.Uuid(), nullable=False),
    sa.Column('date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('volume_l', sa.DECIMAL(precision=12, scale=3), nullable=False),
    sa.Column('price_snapshot', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milk_deliveries_buyer_id'), 'milk_deliveries', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_milk_deliveries_date'), 'milk_deliveries', ['date'], unique=False)
    op.create_index(op.f('ix_milk_deliveries_date_time'), 'milk_deliveries', ['date_time'], unique=False)
    op.create_index(op.f('ix_milk_deliveries_tenant_id'), 'milk_deliveries', ['tenant_id'], unique=False)
    op.create_table('milk_prices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price_per_l', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('buyer_id', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'date', 'buyer_id', name='ux_prices_tenant_date_buyer')
    )
    op.create_index(op.f('ix_milk_prices_buyer_id'), 'milk_prices', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_milk_prices_date'), 'milk_prices', ['date'], unique=False)
    op.create_index(op.f('ix_milk_prices_tenant_id'), 'milk_prices', ['tenant_id'], unique=False)
    op.create_table('milk_productions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('animal_id', sa.Uuid(), nullable=True),
    sa.Column('date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('input_unit', sa.String(length=4), nullable=False),
    sa.Column('input_quantity', sa.DECIMAL(precision=12, scale=3), nullable=False),
    sa.Column('density', sa.DECIMAL(precision=4, scale=2), nullable=False),
    sa.Column('volume_l', sa.DECIMAL(precision=12, scale=3), nullable=False),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milk_productions_animal_id'), 'milk_productions', ['animal_id'], unique=False)
    op.create_index(op.f('ix_milk_productions_date'), 'milk_productions', ['date'], unique=False)
    op.create_index(op.f('ix_milk_productions_date_time'), 'milk_productions', ['date_time'], unique=False)
    op.create_index(op.f('ix_milk_productions_tenant_id'), 'milk_productions', ['tenant_id'], unique=False)
    op.create_table('tenant_configs',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('default_buyer_id', sa.Uuid(), nullable=True),
    sa.Column('default_density', sa.DECIMAL(precision=4, scale=2), nullable=False),
    sa.Column('default_input_unit', sa.String(length=8), nullable=False),
    sa.Column('default_currency', sa.String(length=8), nullable=False),
    sa.Column('default_price_per_l', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='ux_users_email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tenant_configs')
    op.drop_index(op.f('ix_milk_productions_tenant_id'), table_name='milk_productions')
    op.drop_index(op.f('ix_milk_productions_date_time'), table_name='milk_productions')
    op.drop_index(op.f('ix_milk_productions_date'), table_name='milk_productions')
    op.drop_index(op.f('ix_milk_productions_animal_id'), table_name='milk_productions')
    op.drop_table('milk_productions')
    op.drop_index(op.f('ix_milk_prices_tenant_id'), table_name='milk_prices')
    op.drop_index(op.f('ix_milk_prices_date'), table_name='milk_prices')
    op.drop_index(op.f('ix_milk_prices_buyer_id'), table_name='milk_prices')
    op.drop_table('milk_prices')
    op.drop_index(op.f('ix_milk_deliveries_tenant_id'), table_name='milk_deliveries')
    op.drop_index(op.f('ix_milk_deliveries_date_time'), table_name='milk_deliveries')
    op.drop_index(op.f('ix_milk_deliveries_date'), table_name='milk_deliveries')
    op.drop_index(op.f('ix_milk_deliveries_buyer_id'), table_name='milk_deliveries')
    op.drop_table('milk_deliveries')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_buyers_tenant_id'), table_name='buyers')
    op.drop_table('buyers')
    op.drop_index(op.f('ix_attachments_tenant_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_owner_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_animals_tenant_id'), table_name='animals')
    op.drop_table('animals')
    # ### end Alembic commands ###
