"""Initial migration columns for certificates

Revision ID: 38ed425c20f8
Revises: a4ce84757ed3
Create Date: 2025-10-02 23:44:12.953546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38ed425c20f8'
down_revision: Union[str, Sequence[str], None] = 'a4ce84757ed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal_certificates', sa.Column('certificate_name', sa.String(length=255), nullable=True))
    op.add_column('animal_certificates', sa.Column('association_code', sa.String(length=128), nullable=True))
    op.add_column('animal_certificates', sa.Column('notes', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animal_certificates', 'notes')
    op.drop_column('animal_certificates', 'association_code')
    op.drop_column('animal_certificates', 'certificate_name')
    # ### end Alembic commands ###
