"""Add one_time_tokens table

Revision ID: 6249d4f36718
Revises: d7e1b2a4c9f1
Create Date: 2025-10-15 12:28:13.774916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6249d4f36718'
down_revision: Union[str, Sequence[str], None] = 'd7e1b2a4c9f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_one_time_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_auth_one_time_tokens_purpose', 'auth_one_time_tokens', ['purpose'], unique=False)
    op.create_index('ix_auth_one_time_tokens_token', 'auth_one_time_tokens', ['token'], unique=True)
    op.create_index('ix_auth_one_time_tokens_user_id', 'auth_one_time_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auth_one_time_tokens_user_id', table_name='auth_one_time_tokens')
    op.drop_index('ix_auth_one_time_tokens_token', table_name='auth_one_time_tokens')
    op.drop_index('ix_auth_one_time_tokens_purpose', table_name='auth_one_time_tokens')
    op.drop_table('auth_one_time_tokens')
    # ### end Alembic commands ###
