"""Initial migration (lactations, events, parentage, certificate)

Revision ID: a4ce84757ed3
Revises: c0a6f86862f8
Create Date: 2025-10-02 17:09:09.586673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import JSON

# revision identifiers, used by Alembic.
revision: str = 'a4ce84757ed3'
down_revision: Union[str, Sequence[str], None] = 'c0a6f86862f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_certificates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('animal_id', sa.Uuid(), nullable=False),
    sa.Column('registry_number', sa.String(length=128), nullable=True),
    sa.Column('bolus_id', sa.String(length=128), nullable=True),
    sa.Column('tattoo_left', sa.String(length=64), nullable=True),
    sa.Column('tattoo_right', sa.String(length=64), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('breeder', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('farm', sa.String(length=255), nullable=True),
    sa.Column('data', JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_id')
    )
    op.create_index('ix_animal_certificates_registry_number', 'animal_certificates', ['registry_number'], unique=False)
    op.create_index('ix_animal_certificates_tenant_animal', 'animal_certificates', ['tenant_id', 'animal_id'], unique=False)
    op.create_index(op.f('ix_animal_certificates_tenant_id'), 'animal_certificates', ['tenant_id'], unique=False)
    op.create_table('animal_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('animal_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data', JSON(), nullable=True),
    sa.Column('parent_event_id', sa.Uuid(), nullable=True),
    sa.Column('new_status_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_animal_events_tenant_animal_occurred', 'animal_events', ['tenant_id', 'animal_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_animal_events_tenant_id'), 'animal_events', ['tenant_id'], unique=False)
    op.create_index('ix_animal_events_tenant_type', 'animal_events', ['tenant_id', 'type'], unique=False)
    op.create_table('animal_parentage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('relation', sa.String(length=16), nullable=False),
    sa.Column('parent_animal_id', sa.Uuid(), nullable=True),
    sa.Column('external_code', sa.String(length=64), nullable=True),
    sa.Column('external_registry', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('data', JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_animal_parentage_tenant_child', 'animal_parentage', ['tenant_id', 'child_id'], unique=False)
    op.create_index('ix_animal_parentage_tenant_external_code', 'animal_parentage', ['tenant_id', 'external_code'], unique=False)
    op.create_index(op.f('ix_animal_parentage_tenant_id'), 'animal_parentage', ['tenant_id'], unique=False)
    op.create_index('ix_animal_parentage_tenant_relation', 'animal_parentage', ['tenant_id', 'relation'], unique=False)
    op.create_table('lactations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('animal_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('calving_event_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lactations_tenant_animal', 'lactations', ['tenant_id', 'animal_id'], unique=False)
    op.create_index('ix_lactations_tenant_animal_number', 'lactations', ['tenant_id', 'animal_id', 'number'], unique=False)
    op.create_index(op.f('ix_lactations_tenant_id'), 'lactations', ['tenant_id'], unique=False)
    op.create_index('ix_lactations_tenant_status', 'lactations', ['tenant_id', 'status'], unique=False)
    op.add_column('animals', sa.Column('sex', sa.String(length=6), nullable=True))
    op.add_column('animals', sa.Column('dam_id', sa.Uuid(), nullable=True))
    op.add_column('animals', sa.Column('sire_id', sa.Uuid(), nullable=True))
    op.add_column('animals', sa.Column('external_sire_code', sa.String(length=64), nullable=True))
    op.add_column('animals', sa.Column('external_sire_registry', sa.String(length=64), nullable=True))
    op.add_column('animals', sa.Column('disposition_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('animals', sa.Column('disposition_reason', sa.String(length=512), nullable=True))
    op.create_foreign_key(None, 'animals', 'animals', ['dam_id'], ['id'])
    op.create_foreign_key(None, 'animals', 'animals', ['sire_id'], ['id'])
    op.add_column('milk_productions', sa.Column('lactation_id', sa.Uuid(), nullable=True))
    op.create_index('ix_milk_productions_lactation', 'milk_productions', ['lactation_id'], unique=False)
    op.create_index('ix_milk_productions_tenant_animal_date', 'milk_productions', ['tenant_id', 'animal_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_milk_productions_tenant_animal_date', table_name='milk_productions')
    op.drop_index('ix_milk_productions_lactation', table_name='milk_productions')
    op.drop_column('milk_productions', 'lactation_id')
    op.drop_constraint(None, 'animals', type_='foreignkey')
    op.drop_constraint(None, 'animals', type_='foreignkey')
    op.drop_column('animals', 'disposition_reason')
    op.drop_column('animals', 'disposition_at')
    op.drop_column('animals', 'external_sire_registry')
    op.drop_column('animals', 'external_sire_code')
    op.drop_column('animals', 'sire_id')
    op.drop_column('animals', 'dam_id')
    op.drop_column('animals', 'sex')
    op.drop_index('ix_lactations_tenant_status', table_name='lactations')
    op.drop_index(op.f('ix_lactations_tenant_id'), table_name='lactations')
    op.drop_index('ix_lactations_tenant_animal_number', table_name='lactations')
    op.drop_index('ix_lactations_tenant_animal', table_name='lactations')
    op.drop_table('lactations')
    op.drop_index('ix_animal_parentage_tenant_relation', table_name='animal_parentage')
    op.drop_index(op.f('ix_animal_parentage_tenant_id'), table_name='animal_parentage')
    op.drop_index('ix_animal_parentage_tenant_external_code', table_name='animal_parentage')
    op.drop_index('ix_animal_parentage_tenant_child', table_name='animal_parentage')
    op.drop_table('animal_parentage')
    op.drop_index('ix_animal_events_tenant_type', table_name='animal_events')
    op.drop_index(op.f('ix_animal_events_tenant_id'), table_name='animal_events')
    op.drop_index('ix_animal_events_tenant_animal_occurred', table_name='animal_events')
    op.drop_table('animal_events')
    op.drop_index(op.f('ix_animal_certificates_tenant_id'), table_name='animal_certificates')
    op.drop_index('ix_animal_certificates_tenant_animal', table_name='animal_certificates')
    op.drop_index('ix_animal_certificates_registry_number', table_name='animal_certificates')
    op.drop_table('animal_certificates')
    # ### end Alembic commands ###
