name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.8.3'
      - name: Install dependencies
        run: |
          poetry install
      - name: Lint
        run: |
          poetry run ruff check src tests
      - name: Test
        run: |
          poetry run pytest
      - name: Docker build
        run: |
          docker build -t lechefacil-backend:ci .
