name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
      APP_SERVICE_NAME: lechefacil-backend
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "$GITHUB_TOKEN" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build image
        env:
          IMAGE_SHA: ghcr.io/${{ github.repository }}:${{ github.sha }}
          IMAGE_LATEST: ghcr.io/${{ github.repository }}:latest
        run: |
          IMAGE=$(echo "$IMAGE_SHA" | tr '[:upper:]' '[:lower:]')
          LATEST=$(echo "$IMAGE_LATEST" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "IMAGE_LATEST=$LATEST" >> $GITHUB_ENV
          docker build -t "$IMAGE" -t "$LATEST" .

      - name: Push image tags
        run: |
          docker push "$IMAGE"
          docker push "$IMAGE_LATEST"

      - name: Setup Railway CLI
        run: |
          npm install -g @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ env.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ env.RAILWAY_PROJECT_ID }}
        run: |
          railway service set "$APP_SERVICE_NAME" --image "$IMAGE" --project "$RAILWAY_PROJECT_ID"
          railway service redeploy "$APP_SERVICE_NAME" --project "$RAILWAY_PROJECT_ID"
